// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpecilisteServiceApi.DbContexts;

#nullable disable

namespace SpecilisteServiceApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230124154909_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SpecilisteServiceApi.Models.Specialist", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("joined")
                        .HasColumnType("datetime2");

                    b.Property<string>("street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Specialists");

                    b.HasData(
                        new
                        {
                            id = "afc9354c-f919-438b-9a69-2aa689477dba",
                            Email = "Bouzri@gmail.com",
                            FirstName = "Mohamed",
                            Image = "https://ilchiro.org/wp-content/uploads/2019/06/storyblocks-happy-doctor-standing-with-a-laptop_S8lrSrNa-z-1-1280x640.jpg",
                            LastName = "Bouzri",
                            Speciality = "Medcin",
                            Tel = "06555891",
                            city = "Casablanca",
                            joined = new DateTime(2023, 1, 24, 7, 49, 9, 546, DateTimeKind.Local).AddTicks(3778)
                        },
                        new
                        {
                            id = "2ca13c16-72e1-42bb-b75b-c106e84036de",
                            Email = "sanae@gmail.com",
                            FirstName = "Sanae",
                            Image = "https://ilchiro.org/wp-content/uploads/2019/06/storyblocks-happy-doctor-standing-with-a-laptop_S8lrSrNa-z-1-1280x640.jpg",
                            LastName = "Bouzri",
                            Speciality = "Medcin",
                            Tel = "06555891",
                            city = "rabat",
                            joined = new DateTime(2023, 1, 24, 7, 49, 9, 546, DateTimeKind.Local).AddTicks(3836)
                        },
                        new
                        {
                            id = "92754c30-1149-4d99-b379-0e0d2a4d0373",
                            Email = "jana@gmail.com",
                            FirstName = "Jana",
                            Image = "https://ilchiro.org/wp-content/uploads/2019/06/storyblocks-happy-doctor-standing-with-a-laptop_S8lrSrNa-z-1-1280x640.jpg",
                            LastName = "Bouzri",
                            Speciality = "Medcin",
                            city = "Tanger",
                            joined = new DateTime(2023, 1, 24, 7, 49, 9, 546, DateTimeKind.Local).AddTicks(3848)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
